# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
    # Post GitHub PR comment with validation results
    - bash: |
        source '$(System.DefaultWorkingDirectory)/terraform-stack-pipeline-pr-comment.sh' validate '$(System.DefaultWorkingDirectory)'
      #  TERRAFORM_COMMAND_PR_COMMENT=${TERRAFORM_COMMAND_PR_COMMENT//\\n/%0D%0A}
      #  echo "##vso[task.setvariable variable=TERRAFORM_COMMAND_PR_COMMENT]$TERRAFORM_COMMAND_PR_COMMENT"
      displayName: 'Comment PR - Terraform Validate'
