# Pipeline renders comment content and, if run for GitHub PR,
# posts the comment to the GitHub PR that triggered the comment.
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
    - bash: |
        echo '$(Build.Reason)'
        echo '$(System.PullRequest.PullRequestNumber)'
        echo ''
        source '$(System.DefaultWorkingDirectory)/terraform-pr-comment.sh' validate '$(System.DefaultWorkingDirectory)' '$(Build.BuildNumber)'
        echo "XXX"
        echo ${TERRAFORM_COMMAND_PR_COMMENT}
        echo "ZZZ"

        echo "##vso[task.setvariable variable=TERRAFORM_COMMAND_PR_COMMENT]$TERRAFORM_COMMAND_PR_COMMENT"
      displayName: 'Comment PR - Terraform Validate'

    - bash: |
        echo "XXX"
        echo "${TERRAFORM_COMMAND_PR_COMMENT}"
        echo "ZZZ"
        echo "$(TERRAFORM_COMMAND_PR_COMMENT)"
        echo "YYY"

    - task: GitHubComment@0
      condition: and(not(eq(variables['System.PullRequest.PullRequestId'], '')), ne(variables['TERRAFORM_COMMAND_PR_COMMENT'], ''))
      inputs:
        gitHubConnection: 'mloskot'
        repositoryName: '$(Build.Repository.Name)'
        comment: $(TERRAFORM_COMMAND_PR_COMMENT)
