# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
    # Post GitHub PR comment with validation results
    - bash: |
        sudo apt-get install -qq - uni2ascii
        source '$(System.DefaultWorkingDirectory)/terraform-stack-pipeline-pr-comment.sh' validate '$(System.DefaultWorkingDirectory)' '$(Build.BuildNumber)'
        echo "XXX"
        echo ${TERRAFORM_COMMAND_PR_COMMENT}
        echo "ZZZ"

        echo "##vso[task.setvariable variable=TERRAFORM_COMMAND_PR_COMMENT]$TERRAFORM_COMMAND_PR_COMMENT"
      displayName: 'Comment PR - Terraform Validate'

    - bash: |
        echo "XXX"
        echo ${TERRAFORM_COMMAND_PR_COMMENT}
        echo "ZZZ"
        echo $(TERRAFORM_COMMAND_PR_COMMENT)
        echo "YYY"
